### ISSUE TITLE
Trying start ranked command

### ISSUE THREAD

**Issue by biber890** [MindustryInside/RankedPlugin#1]
I tried start ranked plugin but when i type command ranked it show me 
This Error
```
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at arc.struct.ObjectMap.containsKey(ObjectMap.java:503)
	at mindustry.core.World.loadMap(World.java:344)
	at mindustry.core.World.loadMap(World.java:339)
	at ranked.RankedPlugin.loadLobby(RankedPlugin.java:293)
	at ranked.RankedPlugin.lambda$registerServerCommands$15(RankedPlugin.java:194)
	at arc.util.CommandHandler.lambda$register$1(CommandHandler.java:125)
	at arc.util.CommandHandler.handleMessage(CommandHandler.java:86)
	at arc.util.CommandHandler.handleMessage(CommandHandler.java:30)
	at mindustry.server.ServerControl.handleCommandString(ServerControl.java:1021)
	at mindustry.server.ServerControl.lambda$new$0(ServerControl.java:55)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:81)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
```
Can you fix it
Thanks

**Comment by nekonya3031** [comment]
Hello, this issue related to outdated plugin dependencies. For fix it we must migrate to last versions of dependencies, which have changed significantly and it can took long time.

**Comment by biber890** [comment]
Oh ok Thank you.
